In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
data = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"

In [10]:
!wget

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

In [42]:
df = pd.read_csv(data)
df.head().T

,0,1,2,3,4
lead_source,organic_search,social_media,referral,paid_ads,referral
industry,technology,technology,retail,manufacturing,manufacturing
employment_status,employed,employed,employed,student,student
location,europe,south_america,europe,NaN,north_america
annual_income,88160.0,72688.0,44697.0,NaN,24062.0
number_of_courses_viewed,3,3,3,3,4
interaction_count,4,7,4,6,5
lead_score,0.64,0.72,0.58,0.57,0.62
converted,1,1,1,0,1

In [43]:
df.isnull().sum() #checking missing values in the data set

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [44]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [45]:
(df.converted=='0').head()

0    False
1    False
2    False
3    False
4    False
Name: converted, dtype: bool

In [47]:
df['industry'].mode()

0    technology
Name: industry, dtype: str

In [48]:
df[['annual_income','lead_score']].fillna(0)

      annual_income  lead_score
0           88160.0        0.64
1           72688.0        0.72
2           44697.0        0.58
3               0.0        0.57
4           24062.0        0.62
...             ...         ...
4995        45834.0        0.37
4996        84831.0        0.51
4997        53636.0        0.75
4998        69430.0        0.79
4999        81355.0        0.99

[5000 rows x 2 columns]

In [49]:
df[['lead_source','industry','employment_status','location']].fillna("NA")

         lead_source       industry employment_status       location
0     organic_search     technology          employed         europe
1       social_media     technology          employed  south_america
2           referral         retail          employed         europe
3           paid_ads  manufacturing           student             NA
4           referral  manufacturing           student  north_america
...              ...            ...               ...            ...
4995  organic_search      education          employed           asia
4996              NA     technology          employed  north_america
4997  organic_search        finance          employed           asia
4998        referral     technology          employed         africa
4999        referral     technology          employed         europe

[5000 rows x 4 columns]

In [50]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [56]:
df_corr_matrix = df.corr(numeric_only =True)
abs_corr = df_corr_matrix.abs().unstack().drop_duplicates() # dropping the self correlation (in case a variable is pairing with itself
biggest_corr = abs_corr[abs_corr < 1.0].sort_values(ascending = False) #getting the biggest correlations from variables pairing 
biggest_corr

interaction_count         lead_score                  0.928712
number_of_courses_viewed  lead_score                  0.769352
                          interaction_count           0.721609
lead_score                converted                   0.490206
interaction_count         converted                   0.448624
number_of_courses_viewed  converted                   0.395038
annual_income             lead_score                  0.231396
                          converted                   0.181752
                          number_of_courses_viewed    0.137542
                          interaction_count           0.106375
dtype: float64